### ISSUE TITLE
Voice Region doesnt exist?

### ISSUE THREAD

**Issue by cosmiccreepers** [cosmiccreepers/ukg-discord-bot#8]
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from cogs.utils import context
  File "C:\Users\Tom\Documents\Projects\UKG\Discord-Bot\cogs\utils\__init__.py", line 89, in <module>
    def get_region_string(region: discord.VoiceRegion) -> str:
AttributeError: module 'discord' has no attribute 'VoiceRegion'

**Comment by cosmiccreepers** [comment]
Doesnt appear in logs anymore
